export const SET_USER_ID = 'USER/SET_USER_ID';

export const CONFIRMATION_CODE_SUCCESS = 'USER/CONFIRMATION_CODE_SUCCESS';
export const CONFIRMATION_CODE_REQUEST = 'USER/CONFIRMATION_CODE_REQUEST';
export const CONFIRMATION_CODE_FAILURE = 'USER/CONFIRMATION_CODE_FAILURE';


export const GETTING_KEY_CHANGE_PASSWORD_REQUEST = 'USER/GETTING_KEY_CHANGE_PASSWORD_REQUEST';
export const GETTING_KEY_CHANGE_PASSWORD_SUCCESS = 'USER/GETTING_KEY_CHANGE_PASSWORD_SUCCESS';
export const GETTING_KEY_CHANGE_PASSWORD_FAILURE = 'USER/GETTING_KEY_CHANGE_PASSWORD_FAILURE';

export const SET_PASSWORD_REQUEST = 'USER/SET_PASSWORD_REQUEST';
export const SET_PASSWORD_SUCCESS = 'USER/SET_PASSWORD_SUCCESS';
export const SET_PASSWORD_FAILURE = 'USER/SET_PASSWORD_FAILURE';

export const CLEAR_ERROR = 'USER/CLEAR_ERROR';
export const CANCEL_CONFIRMATION = 'USER/CANCEL_CONFIRMATION';

export const LOGIN_SUCCESS = 'USER/LOGIN_SUCCESS';
export const LOGIN_REQUEST = 'USER/LOGIN_REQUEST';
export const LOGIN_FAILURE = 'USER/LOGIN_FAILURE';


export const LOGIN_LOGOUT = 'USER/LOGIN_LOGOUT';

export const OPEN_GET_CODE = 'USER/OPEN_GET_CODE';






