export const OPEN_CARD_MAKET_REQUEST        = 'OPEN_CARD_MAKET_REQUEST'
export const OPEN_CARD_MAKET_FAILURE        = 'OPEN_CARD_MAKET_FAILURE'
export const OPEN_CARD_MAKET_SUCCESS        = 'OPEN_CARD_MAKET_SUCCESS'
export const ADD_TASK                       = 'ADD_TASK'
export const OPEN_EDIT_TASK_REQUEST         = 'OPEN_EDIT_TASK_REQUEST'
export const OPEN_EDIT_TASK_FAILURE         = 'OPEN_EDIT_TASK_FAILURE'
export const OPEN_EDIT_TASK_SUCCESS         = 'OPEN_EDIT_TASK_SUCCESS'
export const CANCEL_TASK_EDITING            = 'CANCEL_TASK_EDITING'
export const SAVE_TASK_REQUEST              = 'SAVE_TASK_REQUEST'
export const SAVE_TASK_FAILURE              = 'SAVE_TASK_FAILURE'
export const SAVE_TASK_SUCCESS              = 'SAVE_TASK_SUCCESS'
export const REMOVE_TASK_START              = 'REMOVE_TASK_START'
export const REMOVE_TASK_CANCEL             = 'REMOVE_TASK_CANCEL'
export const REMOVE_TASK_REQUEST            = 'REMOVE_TASK_REQUEST'
export const REMOVE_TASK_FAILURE            = 'REMOVE_TASK_FAILURE'
export const REMOVE_TASK_SUCCESS            = 'REMOVE_TASK_SUCCESS'
export const REMOVE_TASK_FILE               = 'REMOVE_TASK_FILE'
export const ADD_TASK_FILE                  = 'ADD_TASK_FILE'
export const EDITING_HTML_TEXT              = 'EDITING_HTML_TEXT'
export const SWITCH_TAB                     = 'SWITCH_TAB'
export const DOWNLOAD_FILE_MAKET_REQUEST    = 'DOWNLOAD_FILE_MAKET_REQUEST'
export const DOWNLOAD_FILE_MAKET_FAILURE    = 'DOWNLOAD_FILE_MAKET_FAILURE'
export const DOWNLOAD_FILE_MAKET_SUCCESS    = 'DOWNLOAD_FILE_MAKET_SUCCESS'
export const UPLOAD_FILE_MAKET_REQUEST      = 'UPLOAD_FILE_MAKET_REQUEST'
export const UPLOAD_FILE_MAKET_FAILURE      = 'UPLOAD_FILE_MAKET_FAILURE'
export const UPLOAD_FILE_MAKET_SUCCESS      = 'UPLOAD_FILE_MAKET_SUCCESS'
export const DOWNLOAD_FILE_TASK_REQUEST     = 'DOWNLOAD_FILE_TASK_REQUEST'
export const DOWNLOAD_FILE_TASK_FAILURE     = 'DOWNLOAD_FILE_TASK_SUCCESS'
export const DOWNLOAD_FILE_TASK_SUCCESS     = 'DOWNLOAD_FILE_TASK_SUCCESS'
export const OPEN_FOLDER_FILES_TASK         = 'OPEN_FOLDER_FILES_TASK'
export const SET_MAKET_STATUS_REQUEST       = 'SET_MAKET_STATUS_REQUEST'
export const SET_MAKET_STATUS_FAILURE       = 'SET_MAKET_STATUS_FAILURE'
export const SET_MAKET_STATUS_SUCCESS       = 'SET_MAKET_STATUS_SUCCESS'

export const CLEAR_MESSAGE                  = 'CLEAR_MESSAGE'
export const SAVE_PROJECT_MAKET                 = 'SAVE_PROJECT_MAKET'

export const REPORTS_REQUEST                = 'REPORTS_REQUEST';
export const REPORTS_SUCCESS                = 'REPORTS_SUCCESS';
export const REPORTS_FAILURE                = 'REPORTS_FAILURE';
export const REPORT_REQUEST                 = 'REPORT_REQUEST';
export const REPORT_SUCCESS                 = 'REPORT_SUCCESS';
export const REPORT_FAILURE                 = 'REPORT_FAILURE';
export const OPEN_FOLDER_REPORT             = 'OPEN_FOLDER_REPORT'
export const MAKET_PROJECTS_REQUEST         = 'MAKET_PROJECTS_REQUEST'
export const MAKET_PROJECTS_FAILURE         = 'MAKET_PROJECTS_FAILURE'
export const MAKET_PROJECTS_SUCCESS         = 'MAKET_PROJECTS_SUCCESS'
export const GET_PROJECT_REQUEST            = 'GET_PROJECT_REQUEST'
export const GET_PROJECT_FAILURE            = 'GET_PROJECT_FAILURE'
export const GET_PROJECT_SUCCESS            = 'GET_PROJECT_SUCCESS'
export const CHANGE_PROJECT_FIELD           = 'CHANGE_PROJECT_FIELD'
export const NEXT_STAGE_REQUEST             = 'NEXT_STAGE_REQUEST'
export const NEXT_STAGE_FAILURE             = 'NEXT_STAGE_FAILURE'
export const NEXT_STAGE_SUCCESS             = 'NEXT_STAGE_SUCCESS'
export const  ADD_PROJECT_FILE              = 'ADD_PROJECT_FILE'
export const  REMOVE_PROJECT_FILE           = 'REMOVE_PROJECT_FILE'
export const  FILLING_CONTROL_FILDS           = 'FILLING_CONTROL_FILDS'


export const CHANGE_MAKETS_STATUS = 'CHANGE_MAKET_STATUS';
export const MAKETS_SGRID_PAGE_CHANGE_PARAMS = 'MAKETS_SGRID_PAGE_CHANGE_PARAMS';
export const MAKETS_FILTER_CHANGE  = 'MAKETS_FILTER_CHANGE';
export const MAKETS_SORT_CHANGE    = 'MAKETS_SORT_CHANGE';
export const MAKETS_REQUEST        = 'MAKETS_REQUEST';
export const MAKETS_SUCCESS        = 'MAKETS_SUCCESS';
export const MAKETS_FAILURE        = 'MAKETS_FAILURE';
export const MAKETS_UPDATE_STATUS_REQUIRED      = 'MAKETS_UPDATE_STATUS_REQUIRED';













